### ISSUE TITLE
[Settings API] Move from DOM to React

### ISSUE THREAD

**Issue by v-briese** [GooseMod/GooseMod#28]
(Edited / taken over by @CanadaHonk)

Moving from DOM-based replication to using Discord's own React components for settings pages.

Also components to be added Settings API side:
 - [ ] Dropdown
 - [ ] Text input

**Comment by CanadaHonk** [comment]
Can't just use the toggle component in DOM, would be part of full DOM to React settings. Changing scope of issue.

**Comment by CanadaHonk** [comment]
Was done with v9 a while ago.
