### ISSUE TITLE
[Patcher] Support for adding to User Popouts

### ISSUE THREAD

**Issue by Cynosphere** [GooseMod/GooseMod#30]
Be able to choose between adding to header, body or the popout entirely, with positional offsets (ex: `addToHeader(/* ... */, -1)` will put it above a user's activities if they have any).

An example of what this could be used for:
![example](https://totallynotavir.us/i/brhu80zm.png)

**Comment by Controlfreak707** [comment]
You can already do that...? Do you mean you want to be able to do this with the API?

**Comment by Cynosphere** [comment]
Is there already an API I don't know about?

**Comment by Controlfreak707** [comment]
> Is there already an API I don't know about?

Try using `goosemodScope.patcher.patch()`

**Comment by Cynosphere** [comment]
> Try using `goosemodScope.patcher.patch()`

I know about that. It would just be better to not have redundancy of every module that wants to add to the user popout to have to patch it on their own.

**Comment by Controlfreak707** [comment]
So then... You want a new API function. Like I said.

**Comment by CanadaHonk** [comment]
Conversation unneeded, says patcher (api) in title.

**Comment by CanadaHonk** [comment]
Closing as not in scope due to future plans.
