### ISSUE TITLE
[Settings] Hiding changelog keeps separator and cannot re-enable

### ISSUE THREAD

**Issue by FjorgeTheHuman** [GooseMod/GooseMod#33]
**Describe the bug**
-  Choosing to hide the changelog setting keeps its separator visible
- Re-enabling the changelog setting does not show it again

**To Reproduce**
1. Go to the settings menu
2. Click on Settings under Goosemod
3. Toggle Goosemod Changelog
4. See first error
5. Toggle Goosemod Changelog again
6. See second error

**Expected behavior**
- When hiding the Changelog, the expected behavior is that the separator which separates the Changelog from the module store to disappear as well
- When re-enabling the Changelog, the expected behavior is that the Changelog setting reappears

**Screenshots**
The changelog is re-enabled but the setting is still hidden
![swappy-20210412_072222](https://user-images.githubusercontent.com/30599715/114387249-bc780200-9b81-11eb-869f-9bdc50202418.png)
Notice the blank area between two separators where the Changelog button would usually be
![swappy-20210412_072210](https://user-images.githubusercontent.com/30599715/114387273-c0a41f80-9b81-11eb-98cd-44a7f64871c1.png)

**GooseMod info:**
 - Update Channel: Release (Togged to dev but didn't restart)
 - Version: 8.0.0 (8af3709)
 - Modules: Not relevant

**Discord info:**
 - Update Channel: Canary
 - OS: Arch Linux
 - Host Version: 0.0.119
 - Web Version: Canary 81996 (c9839c1)

**Other info:**
 - Other Mods: N/A

**Additional context**
I'm unable to check the console for errors because for the longest time, the entire devtools menu has been blank
![swappy-20210412_072555](https://user-images.githubusercontent.com/30599715/114387357-dd405780-9b81-11eb-907e-bee5897fe01d.png)

**Comment by CanadaHonk** [comment]
Verified issues, making fixes.

**Comment by CanadaHonk** [comment]
Fixed in a commit some hours ago.
