### ISSUE TITLE
Breaks local integration with GHUB

### ISSUE THREAD

**Issue by maikirakiwi** [GooseMod/GooseMod#35]
**Describe the bug**
Upon injecting GooseMod, Logitech G Hub integration with Discord (allows me to call internal functions like Mute Self) is broken.

**To Reproduce**
1. Have Logitech G Hub installed (A Logitech peripheral is required)
2. Revoke Authorization with "Logitech G" in "Authorized Apps" under User Settings.
3. Attempt to re-enable Integration under Active Profile > Integration > Discord in G Hub App.
4. Clicking Authorize in Discord does not do anything.

**Expected behavior**
G Hub doesn't seem to detect Discord (or the integration). It's shown as inactive in SDK settings but it should be active.

**Screenshots**
<img src="https://cuddle.moe/Cxc7lkUB.png">
<img src="https://cuddle.moe/NUD7qgw3.png"> 
<img src="https://cuddle.moe/X8BgfjdX.png">

**GooseMod info:**
 - Update Channel: Dev
 - Version: 8.0.0 (1e5f588)
 - Modules: Better Message Deletion; Better NSFW; Copy Avatar URL; Copy Raw

**Discord info:**
 - Update Channel: Stable
 - OS: Windows 10 (10.0.19042)
 - Host Version: 1.0.9001
 - Web Version: Stable 82590 (bf3e4f7)

**Other info:**
 - Authorization Prompt for Integration pop up twice after attempting to re-enable external SDK that connects with Discord.

**Comment by CanadaHonk** [comment]
Do you still have the issue when you remove GooseMod? It shouldn't interfere with anything like this.

**Comment by maikirakiwi** [comment]
> Do you still have the issue when you remove GooseMod? It shouldn't interfere with anything like this.

Nope. It's 100% fine after changing channel back.

**Comment by CanadaHonk** [comment]
Was not a GooseMod issue and was fixed overtime.
