### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CrazyWillBear** [GooseMod/GooseMod#37]
**Describe the bug**
The update keeps saying update failed and loops forever

**To Reproduce**
1. Simply update Goosemod/BetterDiscord and update

**Expected behavior**
It's supposed to just update right away

**Screenshots**
https://media.discordapp.net/attachments/831237416886599722/847329328845160458/unknown.png

(You should be able to find the following information in the bottom of your settings.)

**GooseMod info:**
 - Update Channel: no clue, but uses Goosemod/BetterDiscord
 - Version: can't launch
 - Modules: can't launch

**Discord info:**
 - Update Channel: Canary
 - OS: Windows 10
 - Host Version: idk

**Other info:**
 - Other Mods:BetterDiscord

**Additional context**
N/A

**Comment by CanadaHonk** [comment]
No one else has the issue, what's the contents of your `settings.json`?

**Comment by CrazyWillBear** [comment]
Here it is:
```
{
  "BACKGROUND_COLOR": "#202225",
  "IS_MAXIMIZED": true,
  "IS_MINIMIZED": false,
  "UPDATE_ENDPOINT": "https://updates.goosemod.com/betterdiscord+goosemod",
  "NEW_UPDATE_ENDPOINT": "https://updates.goosemod.com/betterdiscord+goosemod/",
  "WINDOW_BOUNDS": {
    "x": -1611,
    "y": 547,
    "width": 1280,
    "height": 720
  }
}
```

**Comment by CanadaHonk** [comment]
Sorry didn't spot issue, it looks fine, can you try relaunching?

**Comment by CanadaHonk** [comment]
Pretty sure this was a GooseUpdate bug which broke mixing (>1 mod) which was fixed on the same day as when the issue was opened. Closing.
