### ISSUE TITLE
TypeError: process.electronBinding is not a function

### ISSUE THREAD

**Issue by Soitora** [GooseMod/GooseMod#40]
**Describe the bug**
After having updated Discord using the green update icon as usual it now failed to start as it otherwise usually would.

**To Reproduce**
1. Update
1. Now it fails to start

**Expected behavior**
Well I expect the app to be able to start, but after the update just a few minutes ago it doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/10836780/123162804-56f19d00-d471-11eb-8cd7-e5e5075cacaf.png)

**GooseMod info:**
 - Update Channel: `release`, unsure if I set `dev` in the settings though
 - Version: can't check
 - Modules: unsure what I have active, but barely any from Goose

**Discord info:**
 - Update Channel: Development
 - OS: Windows 10 21H1
 - Host Version: 1.0.599
 - Web Version: unsure

**Other info:**
 - Other Mods: BetterDiscord

**Additional context**
Except what I've provided above I'm unsure what additional context I can provide.
Part of the error message includes `...\modules\goose_be...:5940` and `...\modules\goose_be...:6855`

**Comment by smartfrigde** [comment]
This is BetterDiscord issue. Uninject it or use stable. It broke due to Discord updating to Electron 13

**Comment by CanadaHonk** [comment]
See above.

**Comment by Soitora** [comment]
For documentation purposes and someone else sees this and has the same issue, I uninjected **BetterDiscord** just by editing the `settings.json` file again you needed at install, changed `https://updates.goosemod.com/goosemod+betterdiscord` to just `https://updates.goosemod.com/goosemod`.

Note that running the installer to the same file again with just **GooseMod** selected does *not* work, it will make the url become like this: `https://updates.goosemod.com/goosemod+betterdiscord+goosemod`.
