### ISSUE TITLE
[Module Store UI] Modules and themes are missing from store

### ISSUE THREAD

**Issue by FjorgeTheHuman** [GooseMod/GooseMod#44]
**Describe the bug**
There are no modules or themes shown in their respective stores

**To Reproduce**
1. Go to the Settings
2. Click on Plugins or Themes under the Goosemod section

**Expected behavior**
The module store shows a list of modules

**Screenshots**
![image](https://user-images.githubusercontent.com/30599715/125693129-6c959ac3-1e0d-4826-871e-9c2137c18e18.png)
![image](https://user-images.githubusercontent.com/30599715/125693197-a78c721b-57d1-4866-8116-a2d3dbb6689f.png)
Upon switching to the Themes section:
![image](https://user-images.githubusercontent.com/30599715/125693276-c4d9862f-9e16-4015-ac51-addc4f0a1ce4.png)

**GooseMod info:**
 - Update Channel: release, dev
 - Version: GooseMod 9.6.0 (d5c7c9c)
 - Modules: Unable to give full list due to error, but includes (names from settings) WYSIWYG, Sticky Notes, Fuckalytics, Discord Debug, Channel Icons, and Custom CSS

**Discord info:**
 - Update Channel: Canary
 - OS: Arch Linux
 - Host Version: 0.0.126
 - Web Version: Canary 90048 (af1b588)

**Additional context**
Store in Home is disabled

**Comment by CanadaHonk** [comment]
Don't use store in settings, it is known to be buggy. Likely removed or fixed at some point in the future, but low priority as it is discouraged to be used generally anyway.

**Comment by FjorgeTheHuman** [comment]
I see, I hope it's fixed and not removed since I really dislike store in home, but it does work with store in home enabled

**Comment by CanadaHonk** [comment]
Was fixed.
