### ISSUE TITLE
Status Making Screen slows down alot when finished.

### ISSUE THREAD

**Issue by Flam3z** [GooseMod/GooseMod#45]
**Describe the bug**
Discord as a whole tends to slow down alot after I am finishing setting a status and the window very slowly disappears.

**To Reproduce**
1. Go to the status setting section.
2. set any status, nothing specific
3. Click save
**Expected behavior**
Expected Discord not to slow down when only setting a status.

**Screenshots**

(You should be able to find the following information in the bottom of your settings.)

**GooseMod info:**
 - Update Channel: Release
 - Version: GooseMod 10.0.0 (823c656)
 - Modules: fucklytics, Custom sounds, WYSIWYG, clear recent games, channel icons, voicechat utilities, staff tags, custom volume range, arrow down.

**Discord info:**
 - Update Channel: Stable 91104 (7111d55)
 - OS: Windows 10 64-Bit (10.0.18362)
 - Host Version: Host 1.0.9002
 - Web Version: (eg: Canary 75079 (4749c3d))

**Other info:**
 - Other Mods: (eg: BetterDiscord, Powercord)

**Additional context**

**Comment by CanadaHonk** [comment]
"All GooseMod Modules"?

**Comment by Flam3z** [comment]
the modules that are given out the box, if you pick, basic or recommended

**Comment by CanadaHonk** [comment]
That doesn't help, please fill out the template with your actual information.

**Comment by Flam3z** [comment]
updated, my apologies.

**Comment by CanadaHonk** [comment]
Have you tested without GooseMod?

**Comment by Flam3z** [comment]
yes, it doesn't occur.

**Comment by CanadaHonk** [comment]
Closing as GM doesn't touch it so likely Discord / Electron / external bug.
