### ISSUE TITLE
How may one (re)obtain untetheredInject.js?

### ISSUE THREAD

**Issue by Krush206** [GooseMod/GooseMod#46]
A few days ago, I realized https://goosemod-api.netlify.app/untethered/untetheredInject.js was no longer working. Do you (or somebody else) happen to still have _untetheredInject.js_?

Thanks in advance!

**Comment by CanadaHonk** [comment]
Why do you need it? GooseMod hasn't used it since v10.

**Comment by Krush206** [comment]
I use SmartCord, which is dependent upon it. If I only knew of the existence of this file and URL, I would've made a backup of it.

**Comment by CanadaHonk** [comment]
I recommend you stop using SmartCord as it's creator has deprecated it.
