### ISSUE TITLE
[Store] Top Starred errors if a module doesn't have a GitHub entry

### ISSUE THREAD

**Issue by Cynosphere** [GooseMod/GooseMod#54]
**Describe the bug**
Store pages don't load if a module in a repo doesn't have a GitHub entry.
`TypeError: Cannot read property 'stars' of undefined`

**To Reproduce**
1. Add a repository that has a module that doesn't have a `github` key
2. Open Themes or Plugins page (depending on the module type)

**Expected behavior**
Not a blank store page.

**GooseMod info:**
 - Update Channel: dev
 - Version: 12.2 Dev (7fc8e36)
 - Modules: N/A

**Discord info:**
 - Update Channel: Canary 
 - OS: Windows 10
 - Host Version: 1.0.616
 - Web Version: 102597 (80887eb

**Comment by CanadaHonk** [comment]
Was fixed
