### ISSUE TITLE
How to uninstall googse mod and is it safe mod do you collect data or something like passwords etc

### ISSUE THREAD

**Issue by CoderLogy** [GooseMod/GooseMod#64]

**Comment by CanadaHonk** [comment]
Please use the Discord for support and Q&A (as already said). This is for issues like bugs. The answer to your latter question is also no.

**Comment by VilotStar** [comment]
I'm still quite confused as to why the uninstall button in goosemod was removed, was it a security flaw or something?

**Comment by CanadaHonk** [comment]
You cannot just uninstall GooseMod from within the client.

**Comment by CoderLogy** [comment]
Yeah confusing, it makes it difficult to uninstall

**Comment by CoderLogy** [comment]
How?

**Comment by VilotStar** [comment]
> You cannot just uninstall GooseMod from within the client.

There used to be a button for that though, plus having a external script possibly to uninstall it would be a nice addition

**Comment by CanadaHonk** [comment]
It was possible but then was no longer possible as Discord patched something. You can uninstall by deleting the `settings.json`, for Windows the paths are:
- Stable: `%appdata%\discord\settings.json`
- PTB:  `%appdata%\discordptb\settings.json`
- Canary:  `%appdata%\discordcanary\settings.json`
- Development:  `%appdata%\discorddevelopment\settings.json`

Also as said prior, please use the Discord for support/questions and don't revive dead mostly unrelated issues, GitHub isn't meant for this.

**Comment by VilotStar** [comment]
Yeah, I already uninstalled it by just doing a fresh uninstall but thanks for the info and hopefully someone in the same situation can read this and use it and I'm sorry for revive a dead thread

**Comment by CanadaHonk** [comment]
The same uninstall are pinned in the Discord.

**Comment by CoderLogy** [comment]
Thnks Canada honk, I was just helping him anyway or other ha
