### ISSUE TITLE
store tabs sometimes don't work

### ISSUE THREAD

**Issue by KraXen72** [GooseMod/GooseMod#66]
**Describe the bug**
often when going into the plugin or theme store, the installed/store tabs don't do anything and it still displays the store page

**To Reproduce**
1. Go to store
2. Click on installed tab
3. see that the page is still rendering the store rather than installed

**Expected behavior**
installed tab should switch to installed themes/plugins
this bug doesen't occur consistenlty, only around 30% of the time, but when it occurs, a reload is required.
  
**Screenshots**

(You should be able to find the following information in the bottom of your settings.)

**GooseMod info:**
 - Update Channel: dev
 - Version: cc0794f
 - Modules: a few but i doubt they affect this

**Discord info:**
 - Update Channel: stable
 - OS: Windows 10
 - Host Version: 1.0.9004

**Other info:**
 - Other Mods: none

**Comment by boltalex389** [comment]
Yes, this is also an issue too. always have to go to one of my dm's first to get into the store. GUI issue?

**Comment by boltalex389** [comment]
It might be a possible GUI issue.

**Comment by CanadaHonk** [comment]
Was fixed.
