### ISSUE TITLE
[Bug] Store In Home breaks plugins that modify ConnectedPrivateChannelsList

### ISSUE THREAD

**Issue by V3L0C1T13S** [GooseMod/GooseMod#69]
**Describe the bug**
The Store In Home option causes ConnectedPrivateChannelsList to have an additional anonymous child added to it, breaking most plugins that try to modify it. Take for example, this pseudo-code which adds a dashboard to the list.
```ts
if (res.props.children.props.children instanceof Array) {
   /** Works with Store In Home off */
    console.log("not using workaround");
    res.props.children.props.children.push(
    <>
      <Dashboard />
    </>
  );
} else {
  /** Only called if Store In Home is on */
  console.log("workaround applied");
  res.props.children.props.children.props.children.push(
    <>
      <Dashboard />
    </>
  )
}
```

**To Reproduce**
1. Go to Goosemod settings
2. Turn on Store In Home
3. Try to use a plugin/client that modifies the list

**Expected behavior**
Store In Home should not add an additional child to ConnectedPrivateChannelsList

**Screenshots**
Store In Home **off**
![image](https://user-images.githubusercontent.com/51764975/167134890-4dd07ec9-e320-46d1-9a98-966b303c86b0.png)

Store In Home **on** (Notice the additional anonymous child in ConnectedPrivateChannelsList)
![image](https://user-images.githubusercontent.com/51764975/167135993-3d2e69f2-c4bd-4784-9e57-7e645bc959a8.png)

(You should be able to find the following information in the bottom of your settings.)

**GooseMod info:**
 - goosemod.genDebugInfo() output:
 ```
Discord:
Client: desktop
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/1.0.9004 Chrome/91.0.4472.164 Electron/13.6.6 Safari/537.36
Release Channel: stable
Other Mods: 

GooseMod:
GM Version: 12.3 (d46541b9e2cc5c8c87da5f7eabea44606308358a)
GM Branch: null
GM Extension Version: 1.2.0
GM Storage Impl: Extension
Modules: Fucklytics, Custom CSS, Voice User Count
```

**Discord info:**
 - Update Channel: Stable
 - OS: Windows 11 64-bit

**Other info:**
 - Other Mods: Rikka (Unreleased)

**Additional context**

**Comment by CanadaHonk** [comment]
Can screenshot the anonymous component?

**Comment by V3L0C1T13S** [comment]
> Can screenshot the anonymous component?

![image](https://user-images.githubusercontent.com/51764975/167138789-10697578-1f91-45f9-93b0-b3312a1d7a26.png)

**Comment by CanadaHonk** [comment]
Oh, that's GM's hardening. I'd suggest you find in React tree / etc instead of presuming?

**Comment by V3L0C1T13S** [comment]
> Oh, that's GM's hardening. I'd suggest you find in React tree / etc instead of presuming?

Ah, I see. Thanks for the clarification anyway. I'll be sure to use those instead.
