### ISSUE TITLE
Bug Issue

### ISSUE THREAD

**Issue by TheGoldenSun** [GooseMod/GooseMod#80]
**Describe the bug**
Hi Honk, your discord mod is wonderful however your version seems to be outdated 

**To Reproduce**
1. Discord mod not loading properly 
2. Click on plugins are having bug issues please add and improve them from power cord/better discord to your discord mod
3. In reply-notification seems to have loads of bug issues 
4. Profile pictures within the in reply-notification isn't loading properly 

**Expected behavior**
Your discord mod might change since all aliucord do is update their discord mod app and a few plugins but not fixing their own in reply-notification plugin they added themselves.

**Comment by CanadaHonk** [comment]
None of those are GooseMod issues, and use the Discord server for support.

**Comment by TheGoldenSun** [comment]
Yeah well I hate to break or burst your bubble but every single mod creator of Discord would usually know that there's always going to be bug reports from different types of people so I had to say it to you directly but there's always going to be users complaining the same thing over and over even though that they have to explain it to you in your Discord server that has a supporting child so I apologize but it's been an ongoing issue.

Sent from miss moriarty  
 
  On Wed, Aug 10, 2022 at 4:08 PM, ***@***.***> wrote:   


Closed #80 as completed.

**Comment by CanadaHonk** [comment]
None of the bugs you said are GooseMod, they are plugins or something else.

**Comment by TheGoldenSun** [comment]
Also basically you are saying that you're able to manually create your own plugins for your mod is that correct? Instead of using other plugins from better discord? 

Sent from miss moriarty  
 
  On Wed, Aug 10, 2022 at 4:13 PM, ***@***.***> wrote:   


None of the bugs you said are GooseMod, they are plugins or something else.

**Comment by TheGoldenSun** [comment]
GitHub is a social network community, everyone knows this, so you're not denying that you manually created your own plugin for your mind is that correct?

Sent from miss moriarty  
 
  On Wed, Aug 10, 2022 at 4:21 PM, ***@***.***> wrote:   


GooseMod doesn't use any plugins from BD. GitHub is still not the place for this but okay.

**Comment by CanadaHonk** [comment]
People manage and have rules for their own GitHub repos. I don't know what you mean by your other sentence.

**Comment by TheGoldenSun** [comment]
Rules are suitable for anyone to understand but not to cause trouble, that's the whole point of everyone using github to socially network with each other in their own community groups.
I think you know what I mean you clearly read it so I'm going to ask you a question are you able to manually create your own plug-in for your discord mod? I'm just curious. 

Sent from miss moriarty  
 
  On Wed, Aug 10, 2022 at 4:25 PM, ***@***.***> wrote:   


People manage and have rules for their own GitHub repos. I don't know what you mean by your other sentence.

**Comment by CanadaHonk** [comment]
Yes you can make your own plugins. The main point of GitHub is to host code, it isn't used for chatting or support, Discord exists for that reason.

**Comment by TheGoldenSun** [comment]
Thank you I'm glad you answer the question of my curiosity and to prove my point I'll leave the screenshot here.

Sent from miss moriarty  
 
  On Wed, Aug 10, 2022 at 4:31 PM, ***@***.***> wrote:   


Yes you can make your own plugins. The main point of GitHub is to host code, it isn't used for chatting or support, Discord exists for that reason.
